// <auto-generated />
using ApiKeyPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiKeyPersistence.Migrations
{
    [DbContext(typeof(ApiKeyDbContext))]
    [Migration("20201101220944_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiKeyPersistence.Models.ApiKey", b =>
                {
                    b.Property<string>("KeyString")
                        .HasColumnType("text");

                    b.HasKey("KeyString");

                    b.ToTable("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
